### ISSUE TITLE
Update Quick Start Guide

### ISSUE THREAD

**Issue by jcorde** [CESARBR/knot-documentation#18]
Update Quick Start Guide so it can be more straight forward and accessible for inexperienced users.

- [x] KNoT Thing
- [x] Flash KNoT Gateway 
- [x] Configure KNoT Gateway 
- [x] KNoT Setup App
- [x] Observe Thing through gateway

**Comment by jcorde** [comment]
Close by #20.
